source.ctf.lttng-live: Handle session detach error during finalization
As of Commit 4fb18ad2a9fe1fe95931f1aa2960417b9e558ae2 ("Fix: lib:
assert if an error occurs in
`bt_message_iterator_class_finalize_method`") the thread's
error status is asserted by the library after the finalization of
iterators.

When a relayd disconnects before the Babeltrace2 live viewer is torn
down, the session detach routines fail to receive a reply to the
detach command. In the case of an example application where the
application outlives the relayd, an assert is triggered on cleanup.

    import os
    import socket
    import time

    import bt2

    def is_connected():
        ctf_live_cc = bt2.find_plugin("ctf").source_component_classes["lttng-live"]
        q = bt2.QueryExecutor(ctf_live_cc, "sessions", params={"url": "net://localhost"})
        connected = False
        try:
            for x in q.query():
                print(x)
                if x['session-name'] == 'test' and x['client-count'] >= 1:
                    connected = True
                    break
        except Exception as e:
            print(e)

        return connected

    os.system("lttng create test --live")
    os.system("lttng enable-event -u --all")
    os.system("lttng start")

    ctf_live_cc = bt2.find_plugin("ctf").source_component_classes["lttng-live"]
    iterator = bt2.TraceCollectionMessageIterator(bt2.ComponentSpec(ctf_live_cc, {'inputs': ["net://localhost/host/{}/test".format(socket.gethostname())], 'session-not-found-action': 'end'}))
    data = []
    while not is_connected():
        try:
            data.append(next(iterator))
        except Exception as e:
            print(e)
        time.sleep(0.1)

    os.system("lttng stop")
    del ctf_live_cc
    del iterator
    os.system("lttng destroy")
    input("Press enter to continue")
    os.system("killall lttng-sessiond")
    os.system("killall lttng-relayd")

Running the program prior to this change, the following assert is
seen:

    Spawning a session daemon
    Spawning a relayd daemon
    Live session test created.
    Traces will be output to tcp4://127.0.0.1:5342/ [data: 5343]
    Live timer interval set to 1000000 us
    Enabled user space event rule matching all events and attached to channel `channel0`
    Tracing started for session `test`
    {'session-name': 'test', 'stream-count': 0, 'target-hostname': 'laptop', 'timer-us': 1000000, 'client-count': 0, 'url': 'net://localhost/host/laptop/test'}
    graph object could not run once
    {'session-name': 'test', 'stream-count': 0, 'target-hostname': 'laptop', 'timer-us': 1000000, 'client-count': 1, 'url': 'net://localhost/host/laptop/test'}
    Waiting for data availability
    Tracing stopped for session `test`
    Destroying session `test`..
    Session `test` destroyed
    Press enter to continue
    Error: A file descriptor leak has been detected: 1 tracked file descriptors are still being tracked
    10-18 09:32:28.761 1825475 1825475 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:63 Babeltrace 2 library postcondition not satisfied.
    10-18 09:32:28.761 1825475 1825475 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:65 ------------------------------------------------------------------------
    10-18 09:32:28.761 1825475 1825475 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:66 Condition ID: `post:message-iterator-class-finalize-method:no-error`.
    10-18 09:32:28.761 1825475 1825475 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:68 Function: bt_message_iterator_class_finalize_method().
    10-18 09:32:28.761 1825475 1825475 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:69 ------------------------------------------------------------------------
    10-18 09:32:28.761 1825475 1825475 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:70 Error is:
    10-18 09:32:28.761 1825475 1825475 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:72 Current thread has an error
    10-18 09:32:28.761 1825475 1825475 F LIB/ASSERT-COND bt_lib_assert_cond_failed@lib/assert-cond.c:75 Aborting...
    Aborted

The solution proposed here is to clear the thread's errors and report
them as warnings instead.

Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Change-Id: Icedda6b8550143681873a0b0286981852fb97699
Reviewed-on: https://review.lttng.org/c/babeltrace/+/13362
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>
Tested-by: jenkins <jenkins@lttng.org>