configure: disable -Wdeprecated-literal-operator
With clang 20, we get warnings like:

    /home/smarchi/src/babeltrace/src/cpp-common/vendor/fmt/format.h:4429:27: error: identifier '_a' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
     4429 | constexpr auto operator"" _a(const char* s, size_t) -> detail::udl_arg<char> {
          |                ~~~~~~~~~~~^~
          |                operator""_a

The space is likely there to support g++ 4.8, just like we had to do in
commit ec282adbde1b ("cpp-common/bt2c: adjust syntax of operator"" to
please g++ 4.8").

Since we need to use the deprecated syntax (for g++ 4.8), just disable
the diagnostic.

Change-Id: I7bf128c17faf21bf714ca679ab1145aba6fbfe35
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/14817
Reviewed-by: Michael Jeanson <mjeanson@efficios.com>
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>
Tested-by: jenkins <jenkins@lttng.org>