Fix: tests: Add explicit items method for Mapping compatibility
In Python 3.5, deriving from typing.Mapping does not automatically provide
items/values methods at runtime, unlike in later versions where typing and
collections.abc are somewhat integrated. In those older versions, `typing`
mostly provides "cosmetic" facilities for static analyzers to use and for
documentation purposes.

This leads to issues when the class is used in contexts expecting a
Mapping.

For instance, running ./tests/bindings/python/bt2/test-python-bt2.sh on
Python 3.5.2 results in the following error:

  # Traceback (most recent call last):
  # bindings/python/bt2/test-python-bt2.sh: Traceback (most recent call last):
  #   File "/usr/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
  # bindings/python/bt2/test-python-bt2.sh: File "/usr/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
  #     yield
  # bindings/python/bt2/test-python-bt2.sh: yield
  #   File "/usr/lib/python3.5/unittest/case.py", line 600, in run
  # bindings/python/bt2/test-python-bt2.sh: File "/usr/lib/python3.5/unittest/case.py", line 600, in run
  #     testMethod()
  # bindings/python/bt2/test-python-bt2.sh: testMethod()
  #   File "/home/jenkins/jgalar-build/babeltrace/tests/bindings/python/bt2/test_port.py", line 651, in test_gen_flt_output_ports_iter
  # bindings/python/bt2/test-python-bt2.sh: File "/home/jenkins/jgalar-build/babeltrace/tests/bindings/python/bt2/test_port.py", line 651, in test_gen_flt_output_ports_iter
  #     for port_name, port in comp.output_ports.items():
  # bindings/python/bt2/test-python-bt2.sh: for port_name, port in comp.output_ports.items():
  # AttributeError: '_ComponentPorts' object has no attribute 'items'
  # bindings/python/bt2/test-python-bt2.sh: AttributeError: '_ComponentPorts' object has no attribute 'items'

This commit explicitly defines items and items to trivially return the result of
iterating over the keys.

Change-Id: I8f1e23e6ac98512e6983e7cd82d488c3ad57265f
Signed-off-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/14607