Fix: Use local_typing with Python < 3.5.3
The following error was observed in lttng-tools regression tests on
yocto23-powerpc which uses Python 3.5.2

    ERROR: tools/live/test_early_inactive_app.py
    ============================================

    Traceback (most recent call last):
      File "./tools/live/test_early_inactive_app.py", line 21, in <module>
        import lttngtest
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/master/platform/yocto23-powerpc/src/lttng-tools/tests/utils/lttngtest/__init__.py", line 9, in <module>
        from .environment import *
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/master/platform/yocto23-powerpc/src/lttng-tools/tests/utils/lttngtest/environment.py", line 29, in <module>
        import bt2
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/master/platform/yocto23-powerpc/deps/build/lib/python3.5/site-packages/bt2/__init__.py", line 99, in <module>
        from bt2.graph import Graph
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/master/platform/yocto23-powerpc/deps/build/lib/python3.5/site-packages/bt2/graph.py", line 34, in <module>
        class Graph(bt2_object._SharedObject):
      File "/home/jenkins/workspace/lttng-tools_master_yoctobuild/babeltrace_version/stable-2.1/build/std/conf/std/liburcu_version/master/platform/yocto23-powerpc/deps/build/lib/python3.5/site-packages/bt2/graph.py", line 70, in Graph
        logging_level: bt2_logging.LoggingLevel = bt2_logging.LoggingLevel.NONE,
      File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
        dict(self.__dict__), parameters, _root=True)
      File "/usr/lib/python3.5/typing.py", line 512, in __new__
        for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
      File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
        for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
      File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
        if super().__subclasscheck__(cls):
      File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
        for scls in cls.__subclasses__():
    TypeError: descriptor '__subclasses__' of 'type' object needs an argument
    ERROR: tools/live/test_early_inactive_app.py - missing test plan
    ERROR: tools/live/test_early_inactive_app.py - exited with status 1

This is caused by a bug in Python >= 3.5 and < 3.5.3:
https://github.com/python/typing/issues/266

To avoid running into this issue, use the `local_typing`  module
instead.

Change-Id: I52b94fe15668c014e85f1fea2a9af5ef9fbab92d
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/14422
Reviewed-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>
CI-Build: Simon Marchi <simon.marchi@efficios.com>
Tested-by: jenkins <jenkins@lttng.org>